# Generated by Django 3.1.4 on 2021-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_contributor_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('backend', 'Back-end'), ('frontend', 'Front-end'), ('ios', 'iOS')], max_length=8),
        ),
    ]
