# Generated by Django 3.1.4 on 2021-06-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210625_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='is_manager',
        ),
    ]
